steps:
- name: 'cirrusci/flutter'
  args: ['flutter', 'build', 'web', '--release']
- name: 'gcr.io/allpurpose-1513599929715/firebase'
  args: [ 'deploy', '--token', '${_FIREBASETOKEN}']
images:
 - 'gcr.io/allpurpose-1513599929715/firebase'
