steps:
        - name: 'gcr.io/allpurpose-1513599929715/vuepress'
          args: [ 'build', 'web' ]
        - name: 'gcr.io/allpurpose-1513599929715/firebase'
          args: [ 'deploy', '--token', '${_FIREBASETOKEN}']
          images:
                  - 'gcr.io/allpurpose-1513599929715/flutter_web'
                  - 'gcr.io/allpurpose-1513599929715/firebase'
